---
- name: docker experiment
  hosts: all
  vars:
    docker_user: "{{sec.docker_user}}"
    docker_passwd: "{{sec.docker_passwd}}"
    docker_email: "{{sec.docker_email}}"
  tasks:
  - name: load secrets
    include_vars:
      file: secrets.yaml
      name: sec
  - name: go image
    docker_image:
      name: siuyin/go:dev
  - name: docker login 
    docker_login:
      username: "{{docker_user}}"
      password: "{{docker_passwd}}"
      email: "{{docker_email}}"
  - name: unarchive docker binary
    become: true
    unarchive:
      src: https://download.docker.com/linux/static/stable/x86_64/docker-17.09.0-ce.tgz
      remote_src: yes
      dest: /usr/local/bin
      extra_opts:
        - "--strip-components=1"
        - "docker/docker"
      
#   docker logout only works if the docker command line utillity is present.
#  - name: docker logout
#    docker_login:
#     email: "{{docker_email}}"
#     state: absent

      #  - name: debug
      #    debug:
      #      var: docker_user
      #  - name: debug
      #    debug:
      #      var: docker_passwd
